### ISSUE TITLE
ctrl + shift + delete ?

### ISSUE THREAD

**Issue by minanagehsalalma** [catzsec/ForceAdmin#5]
🤣
![image](https://user-images.githubusercontent.com/20546638/170791173-640131e3-5036-468f-a8ad-154326fc26f2.png)

**Comment by catzsec** [comment]
https://github.com/catzsec/ForceAdmin/discussions/3

**Comment by catzsec** [comment]
No, ctrl + shift + delete does not do anything, if you mean ctrl + alt + delete - please see  https://github.com/catzsec/ForceAdmin/discussions/3
